### ISSUE TITLE
Realizar carregamento de Qualificadores no idioma Francês

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#678]
Realizar carregamento de Qualificadores no idioma Francês tomando como base a página sugerida pelo Arthur.

http://mesh.inserm.fr/FrenchMesh/qualifs.htm

Tomar como orientação o e-mail abaixo:

```
De: Treuherz, Arthur (BIR)
Enviado: quarta-feira, 17 de outubro de 2018 15:47
Para: Brito, Fabio Luis de (BIR); Campos, Ana Cristina Espindola (BIR)
Assunto: RES: DeCS 2018 em francês em ISIS
 
Obrigado Ana.


Fábio, converti a tabela htm abaixo numa base ISIS e copiei para


serverofi4:/home/bases/dec.fre/dec.dec/qualif_fre.mst e .xrf


O campo de abreviatura de duas letras está no campo 3, o qualificador em francês no campo 1, o qualificador em inglês no campo 2, a abreviatura de indexação no campo 4, o sinônimo (apenas uma ocorrência por registro e é um campo opcional: há apenas 5 ocorrências num total de 80 registros) e a definição em francês está no campo 6.


Observe que o qualificador /contraindications foi eliminado. Agora são só 79.


Você pode inserir os termos dessa base no “decs_frances” de 2018 (o campo 2 para o campo 16^i e o campo 1 para o campo 16^f ?


Para o qualificador /políticas, favor incluir o campo 16 com o seguinte conteúdo:


^i/policies^f/politiques


Seria possível enviar novamente para o processamento do iAHx e/ou LILDBIWEB?


Abraço,

Arthur

```

**Comment by falbrito** [comment]
A partir da base preparada por Arthur criei a lista conforme abiaxo:

# Criação da lista
mx qualif_fre "gizmo=$TABS/gansutf8" lw=0 "pft=if p(v3) then v3 fi,'|',if p(v1) then replace(v1,'/','') fi,'|',if p(v5) then v5 fi,'|',if p(v6) then v6/ fi" -all now > lista_qualificadores_frances_UTF8.lst

O script py para importação faz a substituição de " por  ' para poder inserir no MySQL. Isso se fez necessário para a Nota de Escopo.

- Arquivos de processamento:
Arquivo csv: lista_qualificadores_frances_UTF8.lst
Script: insere_qualificadores_FRANCES.py
Tempo de carregamento: 1 m

realizado.

**Comment by falbrito** [comment]
O qualificador "politiques" foi inserido nao mão pois não consta no master "qualif_fre".

Realizado.

**Comment by suelisuga** [comment]
@falbrito @acecampos @arthurtreuherz ,

Como acessamos os descritores e qualificadores em frances no FI-Admin? Onde os acesso? No portal? http://decs.bvsalud.org/

Obrigada!
Sueli

**Comment by arthurtreuherz** [comment]
@suelisuga @falbrito @acecampos @sueli

Ainda não está dispoível para outros usuários de forma pública. Só através da Ana e eu, e Fábio. Pois ainda estamos trabalhando na base 2019. Mas hoje pode ver os termos DeCS em francês pelo FI-ADMIN com a Ana ou Fábio. Fora isso, os descritores em francês do MeSH só no MeSH do Inserm: http://mesh.inserm.fr/FrenchMesh/

Abraço,
Arthur

De: Sueli Mitiko Yano Suga <notifications@github.com>
Enviada em: segunda-feira, 22 de abril de 2019 14:02
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Treuherz, Arthur (BIR) <treuherz@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Realizar carregamento de Qualificadores no idioma Francês (#678)


@falbrito<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalbrito&data=02%7C01%7Ctreuherz%40paho.org%7Cf78a6fdb54f24d94164008d6c74443fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915493351705015&sdata=JpJHBUyZdw8YE6TyVx3s7fShQzeENLyDGiijPZZNxU0%3D&reserved=0> @acecampos<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Facecampos&data=02%7C01%7Ctreuherz%40paho.org%7Cf78a6fdb54f24d94164008d6c74443fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915493351715024&sdata=lTTY9g0%2FtpcWLSih4iQ8aaF0WXlVZ%2B26kgC8Ek3lm0c%3D&reserved=0> @arthurtreuherz<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farthurtreuherz&data=02%7C01%7Ctreuherz%40paho.org%7Cf78a6fdb54f24d94164008d6c74443fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915493351715024&sdata=IlVmPmeAiQGVhkT3CmUudi1ikC9DPl0DdiJaA89cHd4%3D&reserved=0> ,

Como acessamos os descritores e qualificadores em frances no FI-Admin? Onde os acesso? No portal? http://decs.bvsalud.org/<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdecs.bvsalud.org%2F&data=02%7C01%7Ctreuherz%40paho.org%7Cf78a6fdb54f24d94164008d6c74443fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915493351725024&sdata=9yI5v7mYRARO7L6U0z4d7cHqvyf64jQPWgVkP7Zl4zo%3D&reserved=0>

Obrigada!
Sueli

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F678%23issuecomment-485477192&data=02%7C01%7Ctreuherz%40paho.org%7Cf78a6fdb54f24d94164008d6c74443fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915493351725024&sdata=ZDj7wx%2FDsc7lRevZzW3328pamAtlG8sR%2BbeDSXwcpqA%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFIN56CECYPHDB22GWPHKDPRXVRJANCNFSM4F5U2FQA&data=02%7C01%7Ctreuherz%40paho.org%7Cf78a6fdb54f24d94164008d6c74443fb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915493351735033&sdata=mn0pSsje0PIYayeWcD57Nt5WEa5DjlR8ndJOG3t7LFc%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
