### ISSUE TITLE
Termo selecionado no DECS não permanece no registro

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#765]
Problema relatado pelos indexadores da revista Enfermería Universitaria:

Hemos reiniciado la indización en la nueva plataforma, durante el proceso, en la pestaña Indización, se nos solicita ingresar DeCS y seleccionar si este se trata de un descriptor primario, al momento de realizar este paso aparentemente se registra la información. Una vez recabados todos los ítems necesarios para indizar, el último paso es Publicar, al dar clic en esta opción, se nos indica que el ítem Descriptores no ha sido registrado, es decir, el sistema no registra la información capturada, por esta situación no hemos podido finalizar el proceso de al menos 12 artículos. Anexamos capturas de pantalla de esta situación.

![image](https://user-images.githubusercontent.com/47643830/55436938-003bd800-5574-11e9-93b6-f25817eb70ef.png)

![image](https://user-images.githubusercontent.com/47643830/55436944-06ca4f80-5574-11e9-814c-47aefe2b2255.png)

**Comment by AngelicaSAPaula** [comment]
ID 953218
Descritor: Trastorno del Sueño-Vigilia

**Comment by anakatiacamilo** [comment]
Angelica, se ela puder testar nos registros LILACSExpress SciELO e por favor pedir para apagar o primeiro descritor do ID 953218 eu agradeço

Katinha


Analista de Sistemas
Metodologías y Tecnologías de Información

Departamento de Evidência e Inteligência para Ação em Saúde – EIH/AD

<http://bireme.br>BIREME<https://bvsalud.org/>/<http://www.paho.org/bra/>OPAS/OMS<https://www.paho.org/hq/index.php?lang=en> | Tel: +55 11 5576-9817 VoIP: 44827


[cid:47248fc9-d977-4432-b1dd-302f6d64ff5a]

________________________________
De: AngelicaSAPaula <notifications@github.com>
Enviado: quinta-feira, 23 de maio de 2019 16:02:20
Para: bireme/fi-admin
Cc: Camilo, Ana Katia (BIR); Assign
Assunto: Re: [bireme/fi-admin] Termo selecionado no DECS não permanece no registro (#765)


ID 953218
Descritor: Trastorno del Sueño-Vigilia

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F765%3Femail_source%3Dnotifications%26email_token%3DAETAYE5X65WD2YHS64QCE6TPW3S3ZA5CNFSM4HDETCB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWDFX5I%23issuecomment-495344629&data=02%7C01%7Ccamiloan%40paho.org%7C0c2cd2ee6303401f29c408d6dfb12f08%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636942349429647371&sdata=H6WKxfHgfOYzxgaolVtzA1IovebFDKTNitT%2Bkcu%2FhLo%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAETAYE7WCXATZZJSGLYOWITPW3S3ZANCNFSM4HDETCBQ&data=02%7C01%7Ccamiloan%40paho.org%7C0c2cd2ee6303401f29c408d6dfb12f08%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636942349429657364&sdata=BAS4CKjUu4OObREdlFWQyVK3YcIcetxIQW6zuM1A%2Bfw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Me parece que possa ser um problema referente ao navegador dela (versão, extensões instaladas, etc) ou até de algum antivirus do computador que esta causando este comportamento.

Por favor, peça para ela tentar realizar o procedimento de indexação usando o Google Chrome, e caso não dê certo, para que ela realize o teste em outro computador para verificar se não é algo relacionado a antivirus.

Obrigado
Vinicius
