### ISSUE TITLE
Artigos LILACS-Express no Fi-Admin aparecem como publicados no iAHx

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#859]
Os registros da revista "Estud. psicol. (Natal)", no Fi-Admin aparecem como LILACS-Express (o usuário fez a indexação, mas não os publicou). No entanto, ao pesquisar no iAHx, os artigos não aparecem como LILACS-Express e a indexação já está disponível.

![image](https://user-images.githubusercontent.com/47643830/62245431-032ac600-b3b8-11e9-933a-f8f5aa1e3aed.png)

![image](https://user-images.githubusercontent.com/47643830/62245510-26557580-b3b8-11e9-8720-005a4d0ae05d.png)

![image](https://user-images.githubusercontent.com/47643830/62245465-150c6900-b3b8-11e9-8170-c456f97dddbd.png)

![image](https://user-images.githubusercontent.com/47643830/62245544-38371880-b3b8-11e9-9caa-373cf5b74531.png)

![image](https://user-images.githubusercontent.com/47643830/62245736-9d8b0980-b3b8-11e9-9d92-ecaac542643e.png)

**Comment by viniciusandrade** [comment]
@botturam 

Verifiquei pelo Solr que estes registros estão sem a marca **LXP** no elemento **services**. 

Esta marca é verificada no formato de apresentação para mostrar que o registro é LILACS-Express.

Poderia, quando possível, verificar?

Obrigado

**Comment by alvesmarilda** [comment]
=Colegas,

Há mais registros com o mesmo problema (outra revista), conforme relato abaixo:

**Fi-admin**
204600 | Einstein (Säo Paulo); 10 (1), 2012 \| Coronary heart disease patient with implantable cardioverter desfibrilator and electrical storm submitted to ventricular tachycardia ablation | **LILACS-Express |**  

**iAHx**
Coronary heart disease patient with implantable cardioverter desfibrilator and electrical storm submitted to ventricular tachycardia ablation / Paciente coronariopata com cardiodesfibrilador e tempestade elétrica submetido à ablação de taquicardia ventricular
Silva, Nilton José Carneiro da; Valdigem, Bruno Pereira; Luize, Christian; Nogueira, Fernando Lopes; Cirenza, Claudio; Fenelon, Guilherme; Makdisse, Marcia Regina Pinho; Cintra, Fátima Dumas; De Paola, Angelo Amato Vincenzo.
Einstein (Säo Paulo) ; 10(1)jan.-mar. 2012. ilus
Artigo em Inglês, Português | **LILACS | ID: lil-621522**

Alguma posição??
Obrigada

**Comment by botturam** [comment]
Katia,

esse registro é coletado para processamento como "LILACS":

operacao@serverofi5:/bases/fiadmin/databases/lilacs $ mx LILACS "text=621522"
mfn=582293​
  1  "BR1.1"​
  2  "lil-621522"​
  5  "S"​
  6  "as"​
  8  "^gTrue^uhttp://apps.einstein.br/revista/arquivos/PDF/2001-116-117.pdf^yPDF^qpdf^ien"​
  8  "^gTrue^uhttp://apps.einstein.br/revista/arquivos/PDF/2001-116-117_port.pdf^yPDF^qpdf^ipt"​
  9  "a"​
 10  "Silva, Nilton Jos▒ Carneiro da^cS▒o Paulo^1Hospital Israelita Albert Einstein^pBR"​
 10  "Valdigem, Bruno Pereira^cS▒o Paulo^1Hospital Israelita Albert Einstein^pBR"​
 10  "Luize, Christian^cS▒o Paulo^1Universidade Federal de S▒o Paulo^pBR"​
 10  "Nogueira, Fernando Lopes^cS▒o Paulo^1Universidade Federal de S▒o Paulo^pBR"​
 10  "Cirenza, Claudio^cS▒o Paulo^1Universidade Federal de S▒o Paulo^pBR"​
 10  "Fenelon, Guilherme^cS▒o Paulo^1Universidade Federal de S▒o Paulo^pBR"​
 10  "Makdisse, Marcia Regina Pinho^cS▒o Paulo^1Hospital Israelita Albert Einstein^pBR"​
 10  "Cintra, F▒tima Dumas^cS▒o Paulo^1Universidade Federal de S▒o Paulo^pBR"​
 10  "De Paola, Angelo Amato Vincenzo^cS▒o Paulo^1Universidade Federal de S▒o Paulo^pBR"​
 12  "Coronary heart disease patient with implantable cardioverter desfibrilator and electrical storm submitted to ventricular tachycardia ablation^ien"​
 12  "Paciente coronariopata com cardiodesfibrilador e tempestade el▒trica submetido ▒ abla▒▒o de taquicardia ventricular^ipt"​
 30  "Einstein (S▒o Paulo)"​
 31  "10"​
 32  "1"​
 35  "1679-4508"​
 38  "^bilus"​
 40  "en"​
 40  "pt"​
 64  "jan.-mar. 2012"​
 65  "20120300"​
 71  "CASE REPORTS"​
 72  "3"​
 76  "AGED"​
 76  "HUMANS"​
 76  "MALE"​
 84  "2012-06-11"​
 87  "^dCATHETER ABLATION"​
 87  "^dCoronary Disease/surg"​
 87  "^dDEFIBRILLATORS, IMPLANTABLE"​
 87  "^dELECTRIC COUNTERSHOCK"​
 87  "^dELECTROCARDIOGRAPHY"​
 87  "^dTachycardia, Ventricular/surg"​
 88  "^dAmiodarone/ther use"​
 88  "^dCOMBINED MODALITY THERAPY"​
 88  "^dCoronary Disease/compl"​
 88  "^dCoronary Disease/ther"​
 88  "^dEMERGENCIES"​
 88  "^dElectrocardiography/methods"​
 88  "^dPulmonary Disease, Chronic Obstructive/compl"​
 88  "^dRECURRENCE"​
 88  "^dTachycardia, Ventricular/drug ther"​
 88  "^dTachycardia, Ventricular/etiol"​
 91  "2012-04-01T09:00:00"​
 92  "import"​
 93  "2018-10-18T05:00:00"​
 98  "FONTE"​
110  "s"​
113  "p"​
776  "FI-ADMIN^i204600^bLILACS"​
778  "621522"​
779  "lil-621522"​
899  "1.11.0-156"​
904  "LILACS"​

abc,

Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: alvesmarilda <notifications@github.com>
Enviado: sexta-feira, 7 de fevereiro de 2020 11:44
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Bottura, Marcelo (BIR) <botturam@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Artigos LILACS-Express no Fi-Admin aparecem como publicados no iAHx (#859)


=Colegas,

Há mais registros com o mesmo problema (outra revista), conforme relato abaixo:

Fi-admin
204600 | Einstein (Säo Paulo); 10 (1), 2012 | Coronary heart disease patient with implantable cardioverter desfibrilator and electrical storm submitted to ventricular tachycardia ablation | LILACS-Express |

iAHx
Coronary heart disease patient with implantable cardioverter desfibrilator and electrical storm submitted to ventricular tachycardia ablation / Paciente coronariopata com cardiodesfibrilador e tempestade elétrica submetido à ablação de taquicardia ventricular
Silva, Nilton José Carneiro da; Valdigem, Bruno Pereira; Luize, Christian; Nogueira, Fernando Lopes; Cirenza, Claudio; Fenelon, Guilherme; Makdisse, Marcia Regina Pinho; Cintra, Fátima Dumas; De Paola, Angelo Amato Vincenzo.
Einstein (Säo Paulo) ; 10(1)jan.-mar. 2012. ilus
Artigo em Inglês, Português | LILACS | ID: lil-621522

Alguma posição??
Obrigada

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F859%3Femail_source%3Dnotifications%26email_token%3DAEMRPF2X4MIUUK754IV3O7DRBVXWHA5CNFSM4IIKJC5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELDENQQ%23issuecomment-583419586&data=02%7C01%7Cbotturam%40paho.org%7C52356e3853c64f04fd1a08d7abdc4a49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637166834944251286&sdata=ukEmBskYXPNmvoO7e075mbChpJDveUqPsHoKd5pwbR0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEMRPF3UWYUGYTQTWYDILITRBVXWHANCNFSM4IIKJC5A&data=02%7C01%7Cbotturam%40paho.org%7C52356e3853c64f04fd1a08d7abdc4a49%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637166834944261283&sdata=zq1C8qSLpr7ymrdHK4rGqKGdRHnn9Np2BVESHY3HagE%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Conforme verificado com o @falbrito existe uma verificação no processo atual de conversão para XML IAHX que adiciona a marca **LILACSEXPRESS** quando o registro é da LILACS e não contem descritores registrados.

Ficou combinado que a marca **LILACSEXPRESS** será colocada pela API do FI-ADMIN levando-se em consideração o status do registro (status = 0).

**Comment by viniciusandrade** [comment]
@falbrito / @anakatiacamilo 
Conforme combinamos a API agora esta exportando no tag 004 a marca LILACSEXPRESS para registros com status = 0.

Favor verificarem e informar em caso de problemas.

**Comment by falbrito** [comment]
O script **serverofi5:/bases/fiadmin/consolida/tpl/harv_fiadmin.sh** foi alterado para não mais cravar LILACSEXPRESS quando não ocorrer o campo 87.

O processamento foi realizado com êxito.

**Comment by botturam** [comment]
processamento em produção regular. Problema resolvido.
