### ISSUE TITLE
ERRO - Correção de registro: quando tento gravar um registro que já foi publicado -Id_1007193

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#867]
Fiz a correção do registro no FI-Adim e quando vou gravar aparece o seguinte erro, segue a figura

Obrigada
Laís
![Id_1007193 _ARGMSAL](https://user-images.githubusercontent.com/37112458/62549670-487b4780-b83f-11e9-9b29-0ce35f530f63.PNG)

**Comment by anakatiacamilo** [comment]
Lais, este registro estava com a localização para o BR1.1 duplicada por isto não era possível publicar, apaguei a duplicação e publiquei para teste.

**Comment by suelisuga** [comment]
@anakatiacamilo o que significa esse erro?

**Comment by anakatiacamilo** [comment]
@suelisuga significa que o Sistema espera um resultado único, mas tem um retorno de mais de um valor. No caso deste problema especifico o sistema gravou duas vezes as informações locais para o mesmo código de Centro Cooperante, não sei se é por causa de algum problema na rede ou lentidão no sistema. Quando isso acontece eu normalmente apago o que esta duplicado direto no MySQL.

**Comment by suelisuga** [comment]
@anakatiacamilo e @viniciusandrade Obrigada pelos esclarecimentos.

Pensando na causa da duplicação de valores, sería possível evitar que isso ocorra?
Há relatos de que, por motivo de lentidão no sistema, os dados inseridos duplicam... Sería melhor criar um novo issue para identificar a causa dessa duplicação?

Aguardo.

Obrigada!
Sueli

**Comment by renatomurasaki** [comment]
Creio que a causa é clicar no botão de salvar/publicar mais de uma vez. Talvez uma saída seja desabilitar o botão após o primeiro click, impedindo do usuário clicar e duplicar a ação.


________________________________
De: Sueli Mitiko Yano Suga <notifications@github.com>
Enviado: segunda-feira, 19 de agosto de 2019 18:14
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [bireme/fi-admin] ERRO - Correção de registro: quando tento gravar um registro que já foi publicado -Id_1007193 (#867)


@anakatiacamilo<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanakatiacamilo&data=02%7C01%7Cmurasaki%40paho.org%7C1309f5b53905419a09ad08d724ea4577%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637018460916966953&sdata=mlfNhT2wQPw%2FEKWalJ8xFuKOPmmBv8haur%2FjhvhGwTw%3D&reserved=0> e @viniciusandrade<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fviniciusandrade&data=02%7C01%7Cmurasaki%40paho.org%7C1309f5b53905419a09ad08d724ea4577%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637018460916966953&sdata=eGgEew8oVt6Ox342MH%2BiwrF5P0PdW3Wc5LAs2Ym9yn0%3D&reserved=0> Obrigada pelos esclarecimentos.

Pensando na causa da duplicação de valores, sería possível evitar que isso ocorra?
Há relatos de que, por motivo de lentidão no sistema, os dados inseridos duplicam... Sería melhor criar um novo issue para identificar a causa dessa duplicação?

Aguardo.

Obrigada!
Sueli

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F867%3Femail_source%3Dnotifications%26email_token%3DAAJLL2SYCEOUPA2Y6MSJBY3QFMEMRA5CNFSM4IJXEFGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4UKEHY%23issuecomment-522756639&data=02%7C01%7Cmurasaki%40paho.org%7C1309f5b53905419a09ad08d724ea4577%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637018460916976952&sdata=joDg3s3vkXSIUWWme8Cbiu8Uv82CX5vY9Ou1qg1BGK0%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJLL2UJPRUCPZGSEJ3CKS3QFMEMRANCNFSM4IJXEFGA&data=02%7C01%7Cmurasaki%40paho.org%7C1309f5b53905419a09ad08d724ea4577%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637018460916976952&sdata=rFo95%2FjoXOy1GsI5igZQWJxRxgczvPMHMdqJSD8JMhQ%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
