### ISSUE TITLE
Erro ao criar analíticas em registro fonte

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#994]
Uma usuária da Guatemala alegou, duas vezes, erro ao tentar criar novas analíticas nos registos-fonte #1026139 (creio que ela apagou, pois não encontrei de novo) e #1026418.

Tentei criar analíticas com o código BR1.1 e com o código e perfil dela (GT6.9 / LILACS-Express Editor) e deu certo nas duas situações.

Pedi pra ela tentar novamente, mas o erro persiste.

![image](https://user-images.githubusercontent.com/47643830/70349598-c5e1b380-1843-11ea-9254-eea4f812e053.png)

![image](https://user-images.githubusercontent.com/47643830/70349640-e3af1880-1843-11ea-8d03-e3879fbf006a.png)

**Comment by viniciusandrade** [comment]
Angelica,

Também realizei os testes e não consegui reproduzir o erro.

Poderia solicitar mais detalhes sobre o artigo que ela esta tentando inserir no FI-ADMIN?

Pelo que consegui observar  pode ser um problema de caracteres (copy e paste) no título ou no resumo que pode estar causando o erro.

Obrigado,
Vinicius
________________________________
De: AngelicaSAPaula <notifications@github.com>
Enviado: sexta-feira, 6 de dezembro de 2019 16:20
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [bireme/fi-admin] Erro ao criar analíticas em registro fonte (#994)


Uma usuária da Guatemala alegou, duas vezes, erro ao tentar criar novas analíticas nos registos-fonte #1026139 (creio que ela apagou, pois não encontrei de novo) e #1026418.

Tentei criar analíticas com o código BR1.1 e com o código e perfil dela (GT6.9 / LILACS-Express Editor) e deu certo nas duas situações.

Pedi pra ela tentar novamente, mas o erro persiste.

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F47643830%2F70349598-c5e1b380-1843-11ea-9254-eea4f812e053.png&data=02%7C01%7Cantoniov%40paho.org%7Cbfabc75fd94e4d9ec7be08d77a816580%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637112568489734402&sdata=2HVPP3V4OSAcl1teOwcWRpr5uaGXo1FUTEhb8VAYyr8%3D&reserved=0>

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F47643830%2F70349640-e3af1880-1843-11ea-8d03-e3879fbf006a.png&data=02%7C01%7Cantoniov%40paho.org%7Cbfabc75fd94e4d9ec7be08d77a816580%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637112568489744395&sdata=etaRM8CXawwPFS3yc81s7CRzecASZwACeJMni5ZxQ%2BY%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F994%3Femail_source%3Dnotifications%26email_token%3DAACVIZ74C5PTKPW3FWL7TETQXKQY3A5CNFSM4JW7SLK2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H6XPRFA&data=02%7C01%7Cantoniov%40paho.org%7Cbfabc75fd94e4d9ec7be08d77a816580%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637112568489744395&sdata=tCJzvsNhmyzpsStym7mTl7%2Fga0iVhCiNCf2y1DqhNGM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAACVIZ6GEO3IWXFMGY2SCSTQXKQY3ANCNFSM4JW7SLKQ&data=02%7C01%7Cantoniov%40paho.org%7Cbfabc75fd94e4d9ec7be08d77a816580%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637112568489754397&sdata=TBgcYKZRrrRsJCHcOIvuX7WyGHTuieNbx3VabqU46xg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
O erro ocorria ao se deixar o título sem conteúdo. Foi resolvido em https://github.com/bireme/fi-admin/commit/d3a23596538c2eb0d62853c687df0b8dc3a1d6ba
